#!/bin/bash

PWD=`pwd`
WORKDIR=.

cd $WORKDIR

source admin-openrc.sh

echo -n "Stopping master..."
nova delete $1-mpi-master

echo "done"

source minicluster-openrc.sh

for ((i=1;i<=$2;i++))
do
   echo -n "Stopping slave $i..."
   nova delete $1-slave-$i
   echo "done"
done

cd $PWD

