#!/bin/bash

###########################
# jachermocilla@gmail.com #
###########################

PWD=`pwd`
WORKDIR=.

cd $WORKDIR


#Some variables
CLUSTER_NAME=$1 
NUM_SLAVES=$2
MASTER_IMAGE=mpi-master-image
SLAVE_IMAGE=mpi-slave-image
FLAVOR=jach.custom_1_512
USER_DATA_SLAVE_TEMPLATE=$WORKDIR/init-slave.template
USER_DATA_SLAVE=$WORKDIR/$CLUSTER_NAME.init-slave.sh
USER_DATA_MASTER_TEMPLATE=$WORKDIR/init-master.template
USER_DATA_MASTER=$WORKDIR/$CLUSTER_NAME.init-master.sh
MASTER_IP_FILE=$CLUSTER_NAME.master_ip.txt

cp $USER_DATA_MASTER_TEMPLATE $USER_DATA_MASTER
replace MASTER_NAME_VALUE $CLUSTER_NAME-mpi-master -- $USER_DATA_MASTER > /dev/null

source admin-openrc.sh
echo "-->Starting frontend/master node.This may take a while."
nova boot $CLUSTER_NAME-mpi-master --image $MASTER_IMAGE --flavor $FLAVOR --user-data $USER_DATA_MASTER --availability-zone nova:openstack-compute-02 > /dev/null

#delay needed to fully boot the machine
sleep 5m

nova list --name $CLUSTER_NAME-mpi-master --fields Networks | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' > $MASTER_IP_FILE 

MASTER_IP=`cat $MASTER_IP_FILE`

cp $USER_DATA_SLAVE_TEMPLATE $USER_DATA_SLAVE
replace MASTER_IP_VALUE $MASTER_IP -- $USER_DATA_SLAVE > /dev/null

cp $USER_DATA_SLAVE $CLUSTER_NAME.tmp

#associate free floating IP
MASTER_PUBLIC_IP=`nova floating-ip-list | grep None | cut -d '|' -f 2 | head -1 | tr -d ' '`
nova add-floating-ip $CLUSTER_NAME-mpi-master $MASTER_PUBLIC_IP


source minicluster-openrc.sh
for ((i=1;i<=$2;i++))
do
  echo "-->Starting slave node #$i..."
  cp $CLUSTER_NAME.tmp $USER_DATA_SLAVE
  replace SLAVE_NAME_VALUE $CLUSTER_NAME-slave-$i -- $USER_DATA_SLAVE > /dev/null
  nova boot $CLUSTER_NAME-slave-$i --image $SLAVE_IMAGE --flavor $FLAVOR --user-data $USER_DATA_SLAVE > /dev/null
done

#delay needed to fully boot the machines
sleep 5

#cleanup
rm $USER_DATA_MASTER
rm $USER_DATA_SLAVE
rm $MASTER_IP_FILE
rm $CLUSTER_NAME.tmp

echo "------------------------------------------------------------------"
echo "You can now connect to $MASTER_PUBLIC_IP to run your MPI programs."
echo "                           "
echo "    ssh mpiuser@$MASTER_PUBLIC_IP "
echo "                           "
echo "For more information email jachermocilla@gmail.com"
echo "------------------------------------------------------------------"

cd $PWD

